# numpy

- one of the core packages
- many packages are built on top of numpy
- ```numpy``` has been optimized for processing

In [1]:
#import Numpy with standard abbreviation
import numpy as np

# Variables
- can think variables as a name we assign to particular object in python

In [2]:
# assign a small array to variable 'a'
a = np.array( [ [1,1,2], [3,5,8] ] )

when cell is run, variable is stored and its values. 
Can see value in two ways:

In [3]:
a
#output what a is

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)
#output what a is

[[1 1 2]
 [3 5 8]]


## Naming variables
- we will use 'snake_case' for naming variables (in this class)
- preferred way to name variables in python

# Variables and objects
**object**: often encountered in documentations or tutorials.

object is bundle of properties and actions about something specific
ex.:
- object: data frame
- properties: number of rows, names of columns, data created
- actions: selecting a row, adding a column

Variable is name we give a specific object, same object can be referenced by different variables.

ex:
- The Sun (actual star at the center of solar system) = object
- sol = Spanish word for Sun = variable
- soleil = French for Sun = abother variable

object and variable used interchangeably

# Types
each object in python has a type

type = what kind of object it is

can also call it **class**

how we see the type/class of an object:

In [5]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

numpy.ndarray is core object/data type in the NumPy package
able to check the type of an entry in arry by indexing
this means if we are interested about the type in just one thing in our array, we can find out by:

In [6]:
print(a[0,0])
#printing the first row and the first column of the array in a
type(a[0,0])

1


numpy.int64

- numpy.int64
- int=integer
- 64= how much bit of space it is taking up

In [9]:
#how to acess the value 5 in the array a?
print(a[1,1])

5


# Functions

`print` was our example of a python function

A function:
- take in a set of **arguments**, separated by commas, and
- use those arguments to produce some **output**

argument = parameter ; argument is more commonly used

can ask for information about a function by executing ? followed by the function name:

In [10]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in parenthesis
- then a short description of what the function does
- finally, a list of the arguments and a brief explanation of each of them.

Different types of arguments inside the paraenthesis. Roughly speaking, there are two types of srguments:

- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional argument**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`

In [3]:
#example:
#print('changing the default end argument of the print function', ends=':)')


# Attributes & Methods

An object in Python has attributes and methods. 

-**attribute**: a property of an object, a piece of information about it.
-**method**: a procedure associtated with an object, an action where the main ingradient is the object itself.
'
Access a variable's attributes and methods by adding a period '.' at the end of the variable's name

'variable.variable_method()' or
'variable.vairable_attribute'

Example:
methods and attributes of NumPy arrays:

In [4]:
import numpy as np

In [5]:
#define a 3x3 array
var = np.array( [ [1,2,3] , [4,5,6] , [7,8,9] ] )
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#shape: attribute telling us
#the number of elements in each dimension of the array
var.shape

(3, 3)

In [7]:
type(var.shape)

tuple

In [8]:
# ndim is an attribute holding the number of array dimensions
var.ndim

2

In [9]:
type(var.ndim)

int

Notice attributes can have many different data types.

Examples of methods:

In [10]:
#min method for array
#return the minimum value in the array
var.min()

1

In [11]:
type(var.min)

builtin_function_or_method

# R & Python
R:
- doesn't use methods within an object
- functions in R are extrinsic to (outside) the objects they are acting on

Example: recreate getting the min value in an array

In R there would be two separate items: the variable 'var' and a *separate* function 'min' that gets 'var' as a parameter:


```
#this is R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim = c(3,3)
min(var)
```

Using the pipe operator >%> in R's tidyverse is closer to the '.' in Python:

```
var <- array(c(1,4,7,2,5,8,3,6,9), dim = c(3,3)
var >%> min()
```

What is happening?
the pipe '>%>' is passing 'var to the 'min()' as if first argument. This is essentially what  the '.' in Python:
```
var = np.array( [ [1,2,3] , [4,5,6,] , [7,8,9,] ] )
var.min()